name: 'CI - Pipeline de Testes Automatizados'

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch: # Permite a execução manual
  schedule:
    - cron: '0 2 * * *' # Execução agendada rotineira (diária)

jobs:
  cypress-run:
    name: 'Instalar Dependências e Executar Testes'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Alterado de 18 para 20
          cache: 'yarn'

      - name: Instalar Dependências
        run: yarn install --frozen-lockfile # Garante a instalação consistente das dependências

      - name: Executar Bateria de Testes Cypress
        run: yarn test:e2e:run # Executa os testes e2e mapeados via Yarn
        continue-on-error: true # Garante a extração do relatório se algum teste falhar

      # Atendendo à exigência de armazenamento e publicação de relatórios na pipeline
      - name: Armazenar e Publicar Artefatos do Relatório
        uses: actions/upload-artifact@v4
        with:
          name: relatorio-evidencias-cypress
          path: |
            cypress/screenshots/
            cypress/videos/
          retention-days: 5 # Define o tempo de retenção dos artefatos